### ISSUE TITLE
Add peripherals after non-linear elimination- Incorrect $DES

### ISSUE THREAD

**Issue by Alzahra-Hamdan** [pharmpy/pharmpy#710] opened 2022-04-13 12:29 UTC
The differential equations are not correct when add peripheral compartments after non-linear elimination.
![image](https://user-images.githubusercontent.com/93916031/163179785-e048b82e-2e56-4ddb-b507-43121ae62c99.png)

They should be:
`DADT(2) = A(1)*KA + A(2)*(-CLMM*KM/(V*(A(2)/V + KM)) - QP1/V) + A(3)*QP1/VP1`
`DADT(3) = A(2)*QP1/V - A(3)*QP1/VP1`

**Comment by rikardn** [comment] 2022-04-26 14:22
Found the cause. Pharmpy cannot correctly identify VC or V in the out rate to use it for the intercompartmental rate.

**Comment by Alzahra-Hamdan** [comment] 2022-04-27 15:48
With Pharmr 0.68.0, the same issue is still happening for the third compartment in (MM/MIX-FO-MM + P2).

![image](https://user-images.githubusercontent.com/93916031/165558809-66d15ebb-5043-4d4b-95a9-11824559352c.png)

**Comment by Alzahra-Hamdan** [comment] 2022-04-27 15:58
Additionally, a deviation is seen in setting initial estimates for QP1 in (MM elimination+P1) model. 

![image](https://user-images.githubusercontent.com/93916031/165561058-2bf92da0-daf7-491b-873b-559da8a8bf28.png)

**Comment by rikardn** [comment] 2022-04-28 06:14
Ok, I probably only fixed adding one peripheral. Reopening

**Comment by rikardn** [comment] 2022-04-28 10:49
Fixed by 347be1951b8266a66ce9c448b88ae10861be80cc. Should also fix the inits.

**Closed by rikardn** 2022-04-28 10:49 UTC
Labels: bug
