### ISSUE TITLE
run_amd fails when MM elimination is selected by modelsearch

### ISSUE THREAD

**Issue by emiliesg** [pharmpy/pharmpy#2709] opened 2024-02-26 16:05 UTC
### Bug report

Hi, 

Using pharmr v0.106, I run the following AMD process with customized search space: 
_sp <- 'ABSORPTION([FO,SEQ-ZO-FO]); ELIMINATION([FO,MM,MIX-FO-MM]); LAGTIME([OFF,ON]); TRANSITS([0,1,3,10],*); PERIPHERALS([0,1,2])'
run_amd(input="dataset_filtered.csv",
                   search_space = sp,
                   strategy = 'SIR',
                   administration='oral',
                   modeltype = "basic_pk")_

I got the following error, which appears to be after a model with MM elimination was selected:  

_`ValueError: Parameter CL has no iiv.
Run `reticulate::py_last_error()` for details.Full stack:
ValueErrorParameter CL has no iiv.c("  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 477, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 765, in _run_iiv\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 188, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 230, in run_tool_with_name\n    validate_input(*args, **tool_options)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/type.py\", line 60, in _wrapped\n    return fn(*args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/signature.py\", line 48, in _wrapped\n    return fn(*permuted)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/iivsearch/tool.py\", line 336, in validate_input\n    raise ValueError(f\"Parameter {parameter} has no iiv.\")\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/iivsearch/tool.py", line 334, in validate_input
    has_random_effect(model, parameter, "iiv")
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/expressions.py", line 1135, in has_random_effect
    return _depends_on_any_of(model.statements.before_odes, symbol, map(sympy.Symbol, rvs.names))
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/expressions.py", line 1089, in _depends_on_any_of
    raise KeyError(symbol)
KeyError: CL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 477, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 765, in _run_iiv
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 188, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 230, in run_tool_with_name
    validate_input(*args, **tool_options)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/type.py", line 60, in _wrapped
    return fn(*args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/signature.py", line 48, in _wrapped
    return fn(*permuted)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/iivsearch/tool.py", line 336, in validate_input
    raise ValueError(f"Parameter {parameter} has no iiv.")
ValueError: Parameter CL has no iiv.
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.ValueError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = "dataset_filtered.csv", cl_init = init_cl, vc_init = init_vc, mat_init = init_mat, search_space = sp, strategy = "SIR", administration = "oral", modeltype = "basic_pk"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = "dataset_filtered.csv", cl_init = init_cl, vc_init = init_vc, 
    mat_init = init_mat, search_space = sp, strategy = "SIR", administration = "oral", modeltype = "basic_pk"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 0.106.0`_

**Comment by stellabelin** [comment] 2024-02-27 08:14
Hi! This seems like a bug, clearance should always have IIV on it. Maybe there's a bug in the function that detects IIV. Could you attach the model file that is the input file to IIVSearch (found in the `input_model` directory)? Dataset is not needed.

**Comment by emiliesg** [comment] 2024-02-27 08:53
Below is the model file (structural_retries_run5). Note that in metadata.json in iivsearch subfolder I see that keep=CL was used, I am not sure if this can be the reason for the issue.

$PROBLEM PERIPHERALS(1);TRANSITS(1, NODEPOT);ELIMINATION(MM)
$INPUT C STDY ID TIME TIMESCHED TADSCHED AMT DV REGBL EFFBL EVID YTYPE REG DOSE ARM AGE WGT BMI HGT SEX ETHN ALB
$DATA input_model.csv IGNORE=@
$SUBROUTINES ADVAN13 TOL=9
$MODEL COMPARTMENT=(TRANSIT1 DEFDOSE) COMPARTMENT=(TRANSIT2) COMPARTMENT=(CENTRAL) COMPARTMENT=(PERIPHERAL1)
$ABBR REPLACE ETA_CL=ETA(1)
$ABBR REPLACE ETA_VC=ETA(2)
$ABBR REPLACE ETA_MAT=ETA(3)
$PK
KM = THETA(6)
MDT = THETA(3)*EXP(ETA_MAT)
VP1 = THETA(5)
QP1 = THETA(4)
CLMM = THETA(1)*EXP(ETA_CL)
VC = THETA(2)*EXP(ETA_VC)
V1 = VC
Q = QP1
V2 = VP1
K12 = 2/MDT
K23 = 2/MDT
K34 = Q/V1
K43 = Q/V2
$DES
DADT(1) = -A(1)*K12
DADT(2) = A(1)*K12 - A(2)*K23
DADT(3) = A(2)*K23 + A(3)*(-CLMM*KM/(VC*(A(3)/VC + KM)) - K34) + A(4)*K43
DADT(4) = A(3)*K34 - A(4)*K43
$ERROR
IPRED = A(3)/VC
IF (IPRED.EQ.0) THEN
    IPREDADJ = 2.22500000000000E-16
ELSE
    IPREDADJ = IPRED
END IF
Y = IPRED + EPS(1)*IPREDADJ
$THETA  (0,0.059089401323573584) ; POP_CLMM
$THETA  (0,0.12813724602871812) ; POP_VC
$THETA  (0,0.188555665993688) ; POP_MDT
$THETA  (0,0.006519093202342613,999999) ; POP_QP1
$THETA  (0,0.05279869245159818,999999) ; POP_VP1
$THETA  (0,29709.0329793545,270000.0) ; POP_KM
$OMEGA BLOCK(2)
0.11539779711363764	; IIV_CLMM
0.06345090390288131	; IIV_CLMM_IIV_VC
0.28540879612884323	; IIV_VC
$OMEGA  0.2633044375655604 ; IIV_MDT
$SIGMA  0.0423041199875491 ; sigma
$ESTIMATION METHOD=COND INTER MAXEVAL=99999
$TABLE ID TIME DV CWRES PRED CIPREDI FILE=mytab NOAPPEND NOPRINT

**Comment by stellabelin** [comment] 2024-02-28 09:11
Hi! Great, thank you. I can reproduce the error, I think this is because it has CLMM instead of CL, and we always keep IIV on CL. Here AMD should probably automatically keep it on CLMM. Will let you know once we have a fix out.

**Comment by stellabelin** [comment] 2024-03-01 09:43
Fixed in d373aae.

**Closed by stellabelin** 2024-03-01 09:43 UTC
