### ISSUE TITLE
Fix_parameters function

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#121] opened 2021-03-09 07:50 UTC
I managed to fix one or several parameters to some given values or to fix them without any given values. However, I still need to use the "POP_..." names. Fixing using 'THETA(X)' names does not work.

model <- model %>%
   fix_parameters(list('THETA(1)','THETA(4)')) %>% 
  update_source() 

Error in py_call_impl(callable, dots$args, dots$keywords) : KeyError: 'Parameter "THETA(1)" does not exist'

I also tried to fix all parameters as suggested in the doc "If parameter_names is None, all parameters will be transformed.". 
I tested:

> model <- model %>% 
   fix_parameters_to(list(NULL),list(0)) %>% 
   update_source() 

Error in py_call_impl(callable, dots$args, dots$keywords) : KeyError: 'Parameter "None" does not exist'

What is the correct way to test this option? This is not clear to me. 
Kind regards,

Sylvie

**Comment by stellabelin** [comment] 2021-03-09 10:29
Thank you for reporting this, I can reproduce the errors! 

The reason you have to use "POP_"-names is due to how the naming system works (you can read about it [here](https://pharmpy.github.io/latest/nonmem_plugin.html#names-of-parameters-and-random-variables)). In your case, is there a comment with the parameter names? In that case it is your configuration of how parameter names are read that determines that you only can call it using its "POP_"-name. You can change the configuration either by creating a config-file (explained [here](https://pharmpy.github.io/latest/configuration.html)) or using the following line in R:

```
pharmpy$plugins$nonmem$conf$parameter_names <- c('abbr', 'comment', 'basic')
```

If you just set it to 'basic' it will only use the NONMEM-names when reading a model from a file. The naming system does not allow for synonyms of both the internal Pharmpy-name and possible NONMEM-names, which is why you have to use the "POP_"-name if that is in the configuration. To see what your parameters are currently named you can print the parameters.

Regarding using None as input argument, you have to use NULL as input (and not a list), the same for 0. I discovered a bug when doing so (fixed in 6c2e5e344ff2117999c2337fc7bf27ec42dd8c2a), in the next release you should be able to fix all parameters to 0 using the following code:

```
model <- model %>%
  fix_parameters_to(NULL, 0) %>%
  update_source()
```

I will close this issue for now, but you can still comment or reopen if anything is unclear.

**Closed by stellabelin** 2021-03-09 10:29 UTC
