### ISSUE TITLE
Initial estimate naming and removal of IOV

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#561] opened 2022-02-21 09:08 UTC
R:4.1.2, Pharmpy: 0.49.0. When reading in a model (see below), there was an issue with reading the .mod file:

```
> py_last_error()
$type
[1] "ValueError"

$value
[1] "Mismatch in number of parameter names, all have not been accounted for. If basic NONMEM-names are desired as fallback, double-check that \"basic\" is included in config-settings for parameter_names."

$traceback
[1] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\modeling\\remove_iov.py\", line 37, in remove_iov\n    rvs, sset = model.random_variables, model.statements\n"                   
[2] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 689, in random_variables\n    self.statements\n"                                               
[3] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 447, in statements\n    trans_statements, trans_params = self._create_name_trans(statements)\n"
[4] "  File \"C:\\Users\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\lib\\site-packages\\pharmpy\\plugins\\nonmem\\model.py\", line 578, in _create_name_trans\n    raise ValueError(\n"                                           

$message
[1] "ValueError: Mismatch in number of parameter names, all have not been accounted for. If basic NONMEM-names are desired as fallback, double-check that \"basic\" is included in config-settings for parameter_names."
```

the pharmpy.conf reads as follows:

```
[pharmpy.plugins.nonmem]
parameter_names=abbr,comment,basic
default_nonmem_path= c:/nm750
```
If i then copy `; IOV for CL` and `;IOV for V` into the rest of the respective lines i didn't get the error. 
Original code:
```
;Basal FVIII model Clinical data ignored
;PREP (grouped) as covariate on V1
;PREP (grouped) as covariate on CL SAME THETA
;age as covariate on CL only

$PROBLEM 2-comp, allometric scaling, IOV on CL and V
$INPUT ID DAT2=DROP OTIM=DROP TIME DV AMT RATE AGE WT
BLGR PREP EVID OCC YBIN OCC2 STUD
$DATA DataFVIII6.prn IGNORE=(STUD.EQ.1) IGN=@ 
$SUBROUTINES ADVAN3 TRANS4

$PK
Q1 = 0
Q2 = 0
Q3 = 0
Q4 = 0
Q5 = 0
Q6 = 0
Q7 = 0
Q8 = 0
IF(OCC.EQ.1)Q1 = 1
IF(OCC.EQ.2)Q2 = 1
IF(OCC.EQ.3)Q3 = 1
IF(OCC.EQ.4)Q4 = 1
IF(OCC.EQ.5)Q5 = 1
IF(OCC.EQ.6)Q6 = 1
IF(OCC.EQ.7)Q7 = 1
IF(OCC.EQ.8)Q8 = 1

IF (PREP.EQ.1) PREP2 = 1
IF (PREP.EQ.2) PREP2 = 2
IF (PREP.EQ.3) PREP2 = 1
IF (PREP.EQ.4) PREP2 = 1
IF (PREP.EQ.5) PREP2 = 1
IF (PREP.EQ.6) PREP2 = 2
IF (PREP.EQ.7) PREP2 = 2
;IF (PREP.EQ.8) PREP2 = 3
IF (PREP.EQ.9) PREP2 = 2

IF (PREP2.EQ.1) THEN
TVCL = THETA(1)*((WT/68)**THETA(7))*(1+THETA(13)*(AGE-24)) ;68 = Median of body weight
TVV1 = THETA(2)*((WT/68)**THETA(8)) 
ENDIF
IF (PREP2.EQ.2) THEN
TVCL = THETA(1)*((WT/68)**THETA(7))*(1+THETA(12))*(1+THETA(13)*(AGE-24))
TVV1 = THETA(2)*((WT/68)**THETA(8))*(1+THETA(12))
ENDIF
TVQ  = THETA(5)*(WT/68)**THETA(9)
TVV2 = THETA(6)*(WT/68)**THETA(10)
IOVCL= Q1*ETA(4)+Q2*ETA(5)+Q3*ETA(6)+Q4*ETA(7)+Q5*ETA(8)+Q6*ETA(9)+Q7*ETA(10)+Q8*ETA(11)
IOVV = Q1*ETA(12)+Q2*ETA(13)+Q3*ETA(14)+Q4*ETA(15)+Q5*ETA(16)+Q6*ETA(17)+Q7*ETA(18)+Q8*ETA(19)
CL   = TVCL*EXP(ETA(2)+IOVCL)
V1   = TVV1*EXP(ETA(3)+IOVV)
Q    = TVQ
V2   = TVV2

TVBA = THETA(11)
BASE = TVBA*EXP(ETA(1))

S1 = V1

K = CL/V1
K12 = Q/V1
K21 = Q/V2

$ERROR
IPRED = F + BASE
IRES  = DV-IPRED
W     = SQRT(THETA(3)**2 + (THETA(4)*IPRED)**2)
IWRES = IRES/W
IF(W.EQ.0) W = 1

Y = IPRED + W*EPS(1)

$THETA             
(0,250)            ;1 CL (ml/h)
(0,3380)           ;2 V1 (ml)
(0,0.01)           ;3 Add res error (SD, units = U/ml)
(0,0.08)           ;4 Prop res error (Rel SD = CV)
(0,444)            ;5 Q (ml/h)
(0,268)            ;6 V2 (ml)
0.75 FIX           ;7 Scaling for CL
1 FIX              ;8 Scaling for V1
0.75 FIX           ;9 Scaling for Q
1 FIX              ;10 Scaling for V2
(0,0.01)           ;11 Baseline
(-0.2)             ;12 Difference in TVCL and TVV1 for full-lenght recombinant FVIII
(-0.0185,-0.0076,0.055) ;13 Fractional change in CL per year different from 24 years

$OMEGA BLOCK(3)
0.141                 ;varBase
0.0611 0.107          ;covarBase-CL varETACL
0 0.0509 0.0397       ;covar Base-V1 covar CL-V1 varV1

$OMEGA BLOCK(1) 0.0381 ;IOV for CL
$OMEGA BLOCK(1) SAME   
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME   
$OMEGA BLOCK(1) SAME   
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) 0.0410 ;IOV for V
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME   
$OMEGA BLOCK(1) SAME  
$OMEGA BLOCK(1) SAME  

$SIGMA 1 FIX    
$ESTIMATION METHOD=1 INTER PRINT=1 MAXEVAL=9999
$COVARIANCE PRECOND=1 PFCOND=1

$TABLE ID TIME IPRED CWRES
      NOPRINT ONEHEADER FILE=sdtabmod
```

**Comment by pharmpy-dev-123** [comment] 2022-06-21 11:40
@rikardn Pharmpy currently stops at the first non-word symbol after stripping the leading spaces of a comment to create a parameter name. So both OMEGAs will be named `IOV`. Do we want to allow spaces in the names?

@SCarter79 Does reading the `.mod` file works with latest release? I think parsing the input file now works as expected: it does output a warning about bad naming of OMEGAs, names the first one `IOV`, and the second one `OMEGA(12,12)` instead of `IOV for CL` and `IOV for V`. Whether we want to allow spaces in naming is a separate issue. There remains the error raised by `remove_iov` on this model which I am currently investigating.

**Comment by pharmpy-dev-123** [comment] 2022-06-21 13:11
Isn't this a duplicate of #538?

**Comment by pharmpy-dev-123** [comment] 2022-06-21 13:59
I can see at least two problems with the current implementation of `CodeRecord` and `remove_iov` that are raised by the example model in this issue:
  - IF ... THEN ... ENDIF (or "block if") constructs are not mapped one-to-one, or even many-to-one, with `Statement` objects, this makes model `update_source` crash.
  - I recently reimplemented `remove_iov` to detect related `ETA`s when selectively removing `IOV`s. The detection is based on the presence of `Piecewise` assignments to different `ETA`s. The example model in this issue has some level of indirection not detected by the current implementation.

**Comment by rikardn** [comment] 2022-06-22 07:15
I thought the mapping from statements to AST nodes now allowed many to one. Wasn't this needed for fixing the original IOV issue where the NONMEM code wasn't updated correctly?

**Comment by pharmpy-dev-123** [comment] 2022-06-22 07:23
What I have written is not clear enough. The last fix allows many nodes to one statement. Not many statements to one node.

**Comment by rikardn** [comment] 2022-06-22 07:24
Ok, I can check the PR.

I don't think we should allow spaces in names. I tested and both sympy and symengine allows it, but I suspect it can create all sorts of issues down the line. Can you think of any reason for allowing it?

**Comment by pharmpy-dev-123** [comment] 2022-06-22 07:26
As long as the current basic names fallback works I think we can devise whatever format we want for the names. Not allowing spaces seems reasonable but modelers need to be made aware of it. And maybe the warning could be clearer.

**Closed** 2022-07-07 12:52 UTC
