### ISSUE TITLE
Json files - bootstrap

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#177] opened 2021-04-20 07:50 UTC
I cannot create a Json file for a bootstrap.
I have got the following error message:

res=create_results("bootstrap_dir1")
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'NoneType' object has no attribute 'group' 

I will provide you with the bootstrap folder in the box.
Kind regards,

Sylvie

**Comment by rikardn** [comment] 2021-04-27 13:40
Thanks for reporting this. I can reproduce the problem.

**Comment by rikardn** [comment] 2021-04-28 13:44
The bug was triggered because many runs failed and some had bad ext-files. NONMEM sometimes creates ext-files with no header. Pharmpy can now handle this. Fixed with d869e73b29c5c75db81cf48bfe9ee5d5b1d28b14.

**Closed by rikardn** 2021-04-28 13:44 UTC
Labels: bug
