### ISSUE TITLE
run_amd error message regarding TypeError_calculate_confidence_interval_of_quantile()

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#3012] opened 2024-05-13 13:27 UTC
### Bug report

Pharmpy version: 0.110.0

I run the amd tool on cluster. The run seems completed, but it crushed before giving the final result.csv
Here is error message
> moxo.amd <- run_amd(input="moxo_sim_data.csv",
+                     modeltype='basic_pk',
+                     administration='oral',
+                     cl_init=30,
+                     vc_init=100,
+                     mat_init=0.3,
+                     strategy='default',
+                     allometric_variable='WT',
+                     occasion='VISI',
+                     search_space='LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU]); LET(CONTINUOUS, [AGE,RF]);COVARIATE?(@IIV,@CONTINUOUS,EXP);COVARIATE?(@IIV,@CATEGORICAL, CAT)')
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
<Client: 'inproc://172.18.9.147/22778/1' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/10' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/19' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/29' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/38' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/49' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/58' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/68' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/77' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/88' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/97' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/107' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/116' processes=1 threads=10, memory=62.50 GiB>
<Client: 'inproc://172.18.9.147/22778/126' processes=1 threads=10, memory=62.50 GiB>
TypeError: _calculate_confidence_interval_of_quantile() got an unexpected keyword argument 'include_groups'
Full stack:
TypeError_calculate_confidence_interval_of_quantile() got an unexpected keyword argument 'include_groups'c("  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 594, in run_amd\n    final_vpc_plot = vpc_plot(final_model, simulation_data, stratify_on=dvid_name)\n", "  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 1035, in vpc_plot\n    chart = _vpc_plot(model, simulations, binning=binning, nbins=nbins, qi=qi, ci=ci)\n", "  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 844, in _vpc_plot\n    df = _calculate_vpc(\n", 
"  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 755, in _calculate_vpc\n    median_cis = simgroup.apply(\n", "  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py\", line 1363, in apply\n    return self._python_apply_general(f, self._obj_with_exclusions)\n", "  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py\", line 1402, in _python_apply_general\n    values, mutated = self.grouper.apply(f, data, self.axis)\n", 
"  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/ops.py\", line 767, in apply\n    res = f(group)\n", "  File \"/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py\", line 1341, in f\n    return func(g, *args, **kwargs)\n")Traceback (most recent call last):
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1353, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1402, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 767, in apply
    res = f(group)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1341, in f
    return func(g, *args, **kwargs)
TypeError: _calculate_confidence_interval_of_quantile() got an unexpected keyword argument 'include_groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 594, in run_amd
    final_vpc_plot = vpc_plot(final_model, simulation_data, stratify_on=dvid_name)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 1035, in vpc_plot
    chart = _vpc_plot(model, simulations, binning=binning, nbins=nbins, qi=qi, ci=ci)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 844, in _vpc_plot
    df = _calculate_vpc(
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 755, in _calculate_vpc
    median_cis = simgroup.apply(
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1363, in apply
    return self._python_apply_general(f, self._obj_with_exclusions)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1402, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 767, in apply
    res = f(group)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1341, in f
    return func(g, *args, **kwargs)
TypeError: _calculate_confidence_interval_of_quantile() got an unexpected keyword argument 'include_groups'

pharmr version: 0.110.0
'0.110.0'
Pharmpy version: 0.110.0

**Comment by antoniaih** [comment] 2024-05-14 09:34
Can you check what the Python Pandas version is?

**Comment by rosemarychen99** [comment] 2024-05-14 09:46
How can I check the pandas version in R?

**Comment by antoniaih** [comment] 2024-05-14 11:43
You can use `pip show pandas` in a terminal.

**Comment by stellabelin** [comment] 2024-05-14 11:46
If you're using that command in the terminal you need to have your virtual environment activated, from R you can use `reticulate::py_list_packages()`.

**Comment by liangqiongyue** [comment] 2024-09-18 07:59
> If you're using that command in the terminal you need to have your virtual environment activated, from R you can use `reticulate::py_list_packages()`.
@stellabelin Hi, I have the same problem, can you help me see how to solve it?
`amd.result <- run_amd(input="data.csv",  modeltype='basic_pk', administration='oral', cl_init=30, vc_init=100,mat_init=0.3,                
                      strategy='default', allometric_variable='WT', occasion='VISI',search_space='LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU])')`
then I got the results:
`Full stack:
ValueError: `search_space` evaluated to be empty : "LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU])
Run `reticulate::py_last_error()` for details.ValueError`search_space` evaluated to be empty : "LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU])c("  File \"C:\\Users\\11566\\AppData\\Roaming\\Python\\Python311\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 216, in run_amd\n    to_be_skipped = validate_input(**args)\n                    ^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\11566\\AppData\\Roaming\\Python\\Python311\\site-packages\\pharmpy\\internals\\fn\\type.py\", line 60, in _wrapped\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\11566\\AppData\\Roaming\\Python\\Python311\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 1192, in validate_input\n    raise ValueError(f'`search_space` evaluated to be empty : \"{search_space}')\n"
)Traceback (most recent call last):
  File "C:\Users\11566\AppData\Roaming\Python\Python311\site-packages\pharmpy\tools\amd\run.py", line 216, in run_amd
    to_be_skipped = validate_input(**args)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\11566\AppData\Roaming\Python\Python311\site-packages\pharmpy\internals\fn\type.py", line 60, in _wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\11566\AppData\Roaming\Python\Python311\site-packages\pharmpy\tools\amd\run.py", line 1192, in validate_input
    raise ValueError(f'`search_space` evaluated to be empty : "{search_space}')
ValueError: `search_space` evaluated to be empty : "LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU])
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.ValueError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = "data.csv", modeltype = "basic_pk", administration = "oral", cl_init = 30, vc_init = 100, mat_init = 0.3, strategy = "default", allometric_variable = "WT", occasion = "VISI", search_space = "LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU])"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = "data.csv", modeltype = "basic_pk", administration = "oral", 
    cl_init = 30, vc_init = 100, mat_init = 0.3, strategy = "default", allometric_variable = "WT", occasion = "VISI", search_space = "LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU])"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.2.0
'1.2.0'
Pharmpy version: 1.2.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!`

My Pandas version is:

**Comment by stellabelin** [comment] 2024-09-18 08:54
Hi! Thanks for reporting! This error is happening because you need to specify you structural search space or covariate search space, the defaults can be found here (i.e. if you use this instead it will hopefully work): https://pharmpy.github.io/latest/amd.html#search-space. I saw now in our documentation that the example is incorrect, this will be fixed. I've made two issues: one regarding updating the example (#3314) and one regarding getting a clearer error message (#3315).

**Comment by liangqiongyue** [comment] 2024-09-19 04:59
@stellabelin, Hello, thank you for your reply. I made some modifications to the code (example from the paper: https://doi.org/10.1002/psp4.13222), and this time I encountered the same error as the author. I apologize for including a lot of content below to demonstrate the complete output results.  I tried installing tflite in Python using `pip install tflite`, and it showed a successful installation: "...`Successfully installed tflite-2.10.0`". However, when I ran run_amd(), I still encountered the same error. I'm not sure what the issue is. I'm almost giving up on running AMD using R because I was able to run it successfully using Python. Sigh, but initially, I wanted to use R because I am more familiar with it.
`
amd.result <- run_amd(input="data.csv",  
              modeltype='basic_pk',  
              administration='oral', 
              cl_init=30, 
              vc_init=100, 
              mat_init=0.3, 
              strategy='default',                                 
              allometric_variable='WT',  
              occasion='VISI',  
              search_space='LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU]); LET(CONTINUOUS, [AGE,RF]);COVARIATE?(@IIV,@CONTINUOUS,[LIN,EXP]);COVARIATE?(@IIV,@CATEGORICAL, CAT)')
`
I got the report:


![image](https://github.com/user-attachments/assets/c34de87a-3fe6-4822-9d23-8a1296b1ad38)

**Comment by liangqiongyue** [comment] 2024-10-12 01:01
> Hi! Thanks for testing further. We think this is a bug on Windows via RStudio, could you try running your script as plain R (e.g. from the command line)?
> 
> The issue seems to be when Sphinx (which is used to create the reports) uses STDOUT, reticulate intercepts this process and some sort of race condition seems to be going on.

Hello,
I apologize for the delayed response. I tried your suggestion of running the code in R.exe instead of Rstudio.exe. However, I found that running the code in R.exe was very inconvenient and caused other issues, so I discontinued this approach. Fortunately, I found a solution to the error: `C:\Users\11566\DOCUME~1\VIRTUA~2\R-RETI~1\Lib\site-packages\pharmpy\tools\funcs\summarize_individuals.py:62: UserWarning: tflite is not installed, using NaN for predictions`. The solution involved downloading tflite from the link `https://github.com/pharmpy/tflite-runtime-wheels/releases/download/v2.15.0-pre/tflite_runtime-2.15.0-cp312-cp312-win_amd64.whl` and then installing tflite_runtime-2.15.0-cp312-cp312-win_amd64.whl using pip install. 
However, after doing this, I encountered another error(show as follow picture) which I am unsure how to resolve, and it's frustrating.
![7a31f9d67ea99f710af73ca2444f95ee](https://github.com/user-attachments/assets/f8447ec4-87a3-4a49-a7e6-b45d5ea47a0d)

**Comment by rikardn** [comment] 2024-10-14 09:53
We haven't been able to reproduce the issue on Windows. We are still trying. It doesn't seem to be an issue with Pharmpy itself, but rather some dependency. If possible you could help us with the faultfinding by patching one of the dependencies to see if it helps.

1. Find the file `C:\Users\11566\AppData\Roaming\Python\Python311\site-packages\jupyter_client\launcher.py`
2. Backup the file
3. Just before line 155 (which should be         `proc = Popen(cmd, **kwargs)  # noqa`) insert (it is important to keep the spaces so make sure to copy it exactly as it is below):

```
        import subprocess
        kwargs['stdout'] = subprocess.DEVNULL
        kwargs['stderr'] = subprocess.DEVNULL
        kwargs['stdin'] = subprocess.DEVNULL
 ```

4. Save the changes and try again

**Comment by liangqiongyue** [comment] 2024-10-21 05:29
> We haven't been able to reproduce the issue on Windows. We are still trying. It doesn't seem to be an issue with Pharmpy itself, but rather some dependency. If possible you could help us with the faultfinding by patching one of the dependencies to see if it helps.
> 
> 1. Find the file `C:\Users\11566\AppData\Roaming\Python\Python311\site-packages\jupyter_client\launcher.py`
> 2. Backup the file
> 3. Just before line 155 (which should be         `proc = Popen(cmd, **kwargs)  # noqa`) insert (it is important to keep the spaces so make sure to copy it exactly as it is below):
> 
> ```
>         import subprocess
>         kwargs['stdout'] = subprocess.DEVNULL
>         kwargs['stderr'] = subprocess.DEVNULL
>         kwargs['stdin'] = subprocess.DEVNULL
> ```
> 
> 4. Save the changes and try again

Hi rikardn, thank you very much for your suggestions. I tried your suggestions and modified the file located at "C:\Users\11566\AppData\Roaming\Python\Python311\site-packages\jupyter_client\launcher.py," but I still encountered the same error. Then, I used the same method to modify the file in the virtual environment: "C:\Users\11566\Documents.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\launcher.py," but the error persisted. I have attached the R runtime log for your reference to help identify the issue. Note: The sample code and data I am using come from: https://doi.org/10.1002/psp4.13222 (psp413222-sup-0001-SupinfoS1.zip).
<img width="643" alt="企业微信截图_17294731191023" src="https://github.com/user-attachments/assets/1d85eb24-32be-4e24-a9e4-7a46d5e0e801">
<img width="641" alt="企业微信截图_17294877181161" src="https://github.com/user-attachments/assets/42aa63bc-7e54-40f2-8b60-2ac2afbcadf1">
[pharmpy_Rlog.txt](https://github.com/user-attachments/files/17455418/pharmpy_Rlog.txt)

**Comment by rikardn** [comment] 2024-11-05 15:02
I think that the original issue in here has been resolved (i.e. the `TypeError: _calculate_confidence_interval_of_quantile() got an unexpected keyword argument 'include_groups'` error). To avoid confusion I'll close this issue and we can continue trying to figure out the specific Windows file handle issue in https://github.com/pharmpy/pharmpy/issues/3399

**Closed by rikardn** 2024-11-05 15:02 UTC

**Comment by rikardn** [comment] 2025-02-05 10:41
The `jupyter_client` issue should be fixed in the next version of Pharmpy. See the linked new issue for the commit.
