### ISSUE TITLE
Issue with create_results R command line

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#119] opened 2021-03-02 13:22 UTC
Hi,

When testing the new create_results() function I have the following error message.

![image](https://user-images.githubusercontent.com/75624013/109654501-89922580-7b62-11eb-8427-a2748ae225c5.png)

FYI: When creating a json file for the same bootstrap run but via python it was working well.

If needed, I can share the documents via the dropbox.

Kind regards,
Simon

**Comment by rikardn** [comment] 2021-03-08 14:32
Do you recognize the line of NONMEM code from your model? If it is actually from your model it is the cause of the issue. Is ```PLOG``` a user defined function or vector perhaps?

Otherwise I'll need the bootstrap directory to be able to find the cause of this. If possible you could perhaps upload it to box.

**Comment by SimonBuatois** [comment] 2021-03-11 18:11
Hi Rikard,
PLOG is not a user defined function, it is the protective code routine that performs the LOG operation in NONMEM.

I have uploaded the boostrap_dir in the box Beta test/Pharmpy/Issue119.

Let me know if you need anything else.
Best,
Simon

**Comment by rikardn** [comment] 2021-03-12 08:15
Ah, sorry I missed that. I'll add support.

**Comment by rikardn** [comment] 2021-03-12 08:37
Fixed with 484a37028c332f89943ed8b80048e72a339f6248

**Comment by SimonBuatois** [comment] 2021-03-24 15:12
Hi Rikard, I tried to use your code and faced a second issue:

![image](https://user-images.githubusercontent.com/75624013/112333037-88b06780-8cba-11eb-9980-9d7ef9ff15c9.png)

As you can see, it seems that "COM(1)" command lines are not recognized by pharmpy.

**Comment by rikardn** [comment] 2021-03-24 17:17
Thanks for reporting this. This is again a bug in the parser that was missed by our 200+ model big test suite. I'll reopen.

**Comment by rikardn** [comment] 2021-03-24 17:26
Fixed by e9fb58e0862a19be8fbbb7f82a6d377b4642e435

**Closed by rikardn** 2021-03-24 17:26 UTC
Labels: bug
