### ISSUE TITLE
resmod issue list

### ISSUE THREAD

**Issue by ZheHuang96** [pharmpy/pharmpy#679] opened 2022-04-07 08:03 UTC
1. Chaos between OFVs before and after resmod selection. Sometimes reach the same ofv even the model change, lst file is correct but `modelfit_results.ofv` is wrong. 
2. Selected model name mistake, could relate to the issue above. 
3. Objective function evaluation number MAXEVALS for CWRES model estimation.
4. better have different resmod file directory when running resmod twice, do not cover the previous one.

**Comment by rikardn** [comment] 2022-04-07 14:51
Ok, I think we should set 9999 or even more then. It can be done using  `model.estimation_steps[-1].maximum_evaluations = 9999`

**Comment by ZheHuang96** [comment] 2022-04-08 10:55
Hi Rikard, sorry, I just see your message! Thank you for your suggestion! According to our pervious codes, I have changed the base CWRES model estimation step by `est = EstimationStep('foce', interaction=True, maximum_evaluations= 9999 ) base_model.estimation_steps = EstimationSteps([est])`  and it works:)

**Comment by ZheHuang96** [comment] 2022-04-08 10:58
I just submit my abstract and I will continue tracking other Resmod issues.

**Comment by ZheHuang96** [comment] 2022-04-11 10:17
Here is the script and related model for the last issue. The issue is that when we run the second resmod, the `best_remod` model of 1st resmod will be replaced by the `best_remod` model of 2nd resmod, but other cwres models will be kept. Of course, if we run 3rd resmod, the `best_remod` models of the previous 2 resmod will be replaced by the `best_remod` model of 3rd resmod. Attached is an example, the best_resmod model of 1st resmod should have a time-varying error, but now it has a time-varying+IIV_on_RUV error from 2nd resmod. 
[resmod_debug.zip](https://github.com/pharmpy/pharmpy/files/8463108/resmod_debug.zip)

**Comment by pharmpy-dev-123** [comment] 2022-04-22 15:10
I managed to reproduce 4 on MacOS with some code and data @ZheHuang96 gave me.

**Comment by pharmpy-dev-123** [comment] 2022-04-25 15:15
Issue number 4 happens because when calling resmod a second time with the `best_resmod` output model of another resmod run as input, these lines copy all files matches `/models/{model.name}/*` to the database of the input model. Unexpectedly, this  matches more than 0 files because the input model name is the same as one of the models in the output database (in this case, `best_resmod`). Even the `.mod` file is copied apparently because the `filename_extension` attribute appears out of sync.

https://github.com/pharmpy/pharmpy/blob/master/src/pharmpy/workflows/execute.py#L46-L63

I guess this was designed with `modelfit` in mind. It also overlaps with a request from @rosemarychen99 to have the final results copied to the input model parent folder. But I think it is very dangerous to rely on the input model name in these situations. A different solution is needed.

**Comment by ZheHuang96** [comment] 2022-04-25 20:54
Currently resmod is the only tool that we need to run multiple times(<3), so a workaround is to change the best model name for resmod selection, e.g. best_resmod_{i} per each run, but then I think it needs to be done externally of resmod, resmod can not really check the {i} and Aurelien also mentioned that it may not work because of the database comparsion.

**Comment by pharmpy-dev-123** [comment] 2022-05-03 05:35
Is point 4 fixed with 0.69.0?

**Comment by ZheHuang96** [comment] 2022-05-03 07:13
Yes, I think so

**Closed** 2022-05-03 07:14 UTC
