### ISSUE TITLE
\'NoneType\' object has no attribute \'ofv\'

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1179] opened 2022-09-20 10:28 UTC
The following issue pops up in ruvsearch when using (dataset 1):

```
 res <- run_amd(
  dataset_path,
  modeltype='pk_iv',
  search_space='PERIPHERALS(1)',
  cl_init= CL,
  vc_init= V,
  categorical=c("SEX","RACE"),
  continuous=c("BMI","BSA")
)
```

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2022-09-19 17:33:54,828 - distributed.worker - WARNING - Compute Failed
Key:       results1
Function:  post_process
args:      (<Pharmpy model object base_model>, <Pharmpy model object base_1>, <Pharmpy model object IIV_on_RUV_1>, <Pharmpy model object power_1>, <Pharmpy model object combined_1>, <Pharmpy model object time_varying1_1>, <Pharmpy model object time_varying2_1>, <Pharmpy model object time_varying3_1>)
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'ofv\'")'

2022-09-19 17:33:54,835 - distributed.worker - WARNING - Compute Failed
Key:       start_ruvsearch-results
Function:  execute_task
args:      ((<function _results at 0x7fd9b4e26550>, (<function start at 0x7fd9b4e26790>, <Pharmpy model object base_model>, 4, 0.05, None)))
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'ofv\'")'

<Client: 'inproc://172.17.0.23/335/1' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.23/335/10' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.23/335/19' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.23/335/28' processes=1 threads=12, memory=31.24 GiB>
2.5
<Client: 'inproc://172.17.0.23/335/39' processes=1 threads=12, memory=31.24 GiB>
AttributeError: 'NoneType' object has no attribute 'ofv'
Full stack:
AttributeError'NoneType' object has no attribute 'ofv'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 145, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 230, in _run_ruvsearch\n    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 162, in start\n    next_res = call_workflow(wf, f'results{current_iteration}')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 133, in call_workflow\n    res = client.gather(futures)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 209, in post_process\n    res = calculate_results(models)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py\", line 37, in calculate_results\n    base_ofv = base_model.modelfit_results.ofv\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 145, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 230, in _run_ruvsearch
    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 162, in start
    next_res = call_workflow(wf, f'results{current_iteration}')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 133, in call_workflow
    res = client.gather(futures)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 209, in post_process
    res = calculate_results(models)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py", line 37, in calculate_results
    base_ofv = base_model.modelfit_results.ofv
AttributeError: 'NoneType' object has no attribute 'ofv'

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5
```

**Comment by joaoabr** [comment] 2022-09-20 10:29
same issue using another dataset (dataset2):

```
res <- run_amd(
    dataset_path,
    modeltype='pk_iv',
    search_space='PERIPHERALS(1)',
    cl_init= CL,
    vc_init= V,
    allometric_variable="WGT"
)
```

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Future exception was never retrieved
future: <Future finished exception=TimeoutError('Timeout')>
tornado.util.TimeoutError: Timeout
2022-09-19 20:39:36,653 - distributed.worker - WARNING - Compute Failed
Key:       results1
Function:  post_process
args:      (<Pharmpy model object iivsearch_block_structure_candidate3>, <Pharmpy model object base_1>, <Pharmpy model object IIV_on_RUV_1>, <Pharmpy model object power_1>, <Pharmpy model object combined_1>, <Pharmpy model object time_varying1_1>, <Pharmpy model object time_varying2_1>, <Pharmpy model object time_varying3_1>)
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'ofv\'")'

2022-09-19 20:39:36,667 - distributed.worker - WARNING - Compute Failed
Key:       start_ruvsearch-results
Function:  execute_task
args:      ((<function _results at 0x7f1da5247310>, (<function start at 0x7f1d5e2f5700>, <Pharmpy model object iivsearch_block_structure_candidate3>, 4, 0.05, None)))
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'ofv\'")'

<Client: 'inproc://172.17.0.24/334/1' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.24/334/10' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.24/334/19' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.24/334/28' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.24/334/41' processes=1 threads=12, memory=31.24 GiB>
AttributeError: 'NoneType' object has no attribute 'ofv'
Full stack:
AttributeError'NoneType' object has no attribute 'ofv'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 145, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 230, in _run_ruvsearch\n    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 162, in start\n    next_res = call_workflow(wf, f'results{current_iteration}')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 133, in call_workflow\n    res = client.gather(futures)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 209, in post_process\n    res = calculate_results(models)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py\", line 37, in calculate_results\n    base_ofv = base_model.modelfit_results.ofv\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 145, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 230, in _run_ruvsearch
    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 162, in start
    next_res = call_workflow(wf, f'results{current_iteration}')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 133, in call_workflow
    res = client.gather(futures)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 209, in post_process
    res = calculate_results(models)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py", line 37, in calculate_results
    base_ofv = base_model.modelfit_results.ofv
AttributeError: 'NoneType' object has no attribute 'ofv'

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5
```

**Comment by rikardn** [comment] 2022-09-20 10:30
The basemodel of the residual error models fails. We will make sure that this is allowed so that the procedure can continue. But it would also be interesting for us to figure out why this happened given the base model is such a simple model. Could you perhaps provide us with the model and the dataset to be able to reproduce?

**Comment by joaoabr** [comment] 2022-09-20 10:38
just did so via Box

**Comment by rikardn** [comment] 2022-09-20 12:58
We can run the base model fine with both NONMEM 7.5 and 7.4 so for some reason these runs didn't produce any results on your side. We will make sure that ruvsearch can detect the situation and continue forwarding the input model. A warning might be in place.

**Comment by joaoabr** [comment] 2022-09-20 21:21
Thanks. The files I sent were for dataset2 (2nd case above). Do you want to see also the files for dataset1 (1st case above)?

**Comment by rikardn** [comment] 2022-09-21 06:26
Sure, we could have a look at that too.

**Comment by joaoabr** [comment] 2022-09-22 15:38
files just sent via box

**Comment by ZheHuang96** [comment] 2022-09-23 11:43
Hi, I can run the base model of dataset1 via NONMEM 7.5.0 and 7.4.4, so I guess it should be the same issue with dataset2, it is a pity that we can not reproduce the issue but as Rikard suggested above, we will make sure ruvsearch can handle this situation.

**Comment by joaoabr** [comment] 2022-09-28 17:52
Issue remains with PharmR 0.78.0 (dataset2). This may be due to an issue in our HPC that makes some runs crash - under investigation. As you proposed, if a key run crashes, it would be great to have a fallback that allows the amd tool to continue.

**Comment by joaoabr** [comment] 2022-09-29 12:06
Hi. Identical error with another dataset (dataset 3):

```
res <- run_amd(
     dataset_path,
     modeltype='pk_oral',
     search_space='PERIPHERALS(1);LAGTIME();ELIMINATION(MIX-FO-MM)',
     cl_init= CL,
     vc_init= V,
     mat_init= MAT,
     continuous="AGE",
     categorical="DOSE")
```


```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate5: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate4: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate11: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
2022-09-28 03:30:14,841 - distributed.worker - WARNING - Compute Failed
Key:       results1
Function:  post_process
args:      (<Pharmpy model object iivsearch_block_structure_candidate47>, <Pharmpy model object base_1>, <Pharmpy model object IIV_on_RUV_1>, <Pharmpy model object power_1>, <Pharmpy model object combined_1>, <Pharmpy model object time_varying1_1>, <Pharmpy model object time_varying2_1>, <Pharmpy model object time_varying3_1>)
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'ofv\'")'

2022-09-28 03:30:14,847 - distributed.worker - WARNING - Compute Failed
Key:       start_ruvsearch-results
Function:  execute_task
args:      ((<function _results at 0x7f1f76b848b0>, (<function start at 0x7f1f080e14c0>, <Pharmpy model object iivsearch_block_structure_candidate47>, 4, 0.05, None)))
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'ofv\'")'

<Client: 'inproc://172.17.0.5/334/1' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.5/334/10' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.5/334/19' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.5/334/29' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.5/334/52' processes=1 threads=12, memory=31.24 GiB>
AttributeError: 'NoneType' object has no attribute 'ofv'
Full stack:
AttributeError'NoneType' object has no attribute 'ofv'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 145, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 230, in _run_ruvsearch\n    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 162, in start\n    next_res = call_workflow(wf, f'results{current_iteration}')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 133, in call_workflow\n    res = client.gather(futures)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 209, in post_process\n    res = calculate_results(models)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py\", line 37, in calculate_results\n    base_ofv = base_model.modelfit_results.ofv\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 145, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 230, in _run_ruvsearch
    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 162, in start
    next_res = call_workflow(wf, f'results{current_iteration}')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 133, in call_workflow
    res = client.gather(futures)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 209, in post_process
    res = calculate_results(models)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py", line 37, in calculate_results
    base_ofv = base_model.modelfit_results.ofv
AttributeError: 'NoneType' object has no attribute 'ofv'

pharmr version: 0.78.0
'0.78.0'
Pharmpy version: 0.78.0
```

**Comment by ZheHuang96** [comment] 2022-09-29 12:57
Hi @joaoabr , may I double check with you about the failures? Currently, ruvsearch failed in three dataset cases:

1. Dataset 1 failed in version 0.76.5. Did it still fail in 0.78.0?
2. Dataset 2 failed in both two versions. I also saw here you also used dataset 2 but ruvsearch worked  https://github.com/pharmpy/pharmpy/issues/1204 May I know what is the difference between these two runs?
3. Dataset 3 failed in 0.78.0, Did it succeed in 0.76.5 or there were issues that terminated the process so that it stopped before ruvsearch? 

Thank you so much!

**Comment by joaoabr** [comment] 2022-09-29 14:08
Hi @ZheHuang96. The issue seems to be connected to jobs being sent to our HPC, as the models can be estimated in NONMEM separately, but not when estimated within the amd tool. This issue seems to be more impactful with ruvsearch, but some models in other sub-tools are also crashing for no apparent reason. Our internal IT team is looking into this.

**Comment by ZheHuang96** [comment] 2022-09-29 14:11
Thank you so much for your reply!

**Comment by ZheHuang96** [comment] 2022-10-13 09:32
Hi @joaoabr , I implemented the functionality that will not crash the amd tool when the base RUV model fails. It will be in the next version of Pharmpy/Pharmar. And also it will be precious for us to get the test results from your side when we release the new version. I will reopen the issue so that it would be easy to track.

**Comment by stellabelin** [comment] 2022-11-08 10:23
Hi! Closing this issue since it has been marked as solved and to make it easier to organize the issues. Please reopen if the error persists!

**Closed by stellabelin** 2022-11-08 10:23 UTC
